//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RssReader.Resources.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RssReader.Resources.Lang.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to remove feed.
        /// </summary>
        internal static string AreUSureToRemoveFeed {
            get {
                return ResourceManager.GetString("AreUSureToRemoveFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Come back.
        /// </summary>
        internal static string ComeBack {
            get {
                return ResourceManager.GetString("ComeBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database error .
        /// </summary>
        internal static string DbError {
            get {
                return ResourceManager.GetString("DbError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit without saving.
        /// </summary>
        internal static string ExitWithoutSaving {
            get {
                return ResourceManager.GetString("ExitWithoutSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed action.
        /// </summary>
        internal static string FeedAction {
            get {
                return ResourceManager.GetString("FeedAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input data error.
        /// </summary>
        internal static string InputDataError {
            get {
                return ResourceManager.GetString("InputDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link can not be empty.
        /// </summary>
        internal static string LinkCantBeEmpty {
            get {
                return ResourceManager.GetString("LinkCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link format error.
        /// </summary>
        internal static string LinkFormatError {
            get {
                return ResourceManager.GetString("LinkFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can not be empty.
        /// </summary>
        internal static string NameCantBeEmpty {
            get {
                return ResourceManager.GetString("NameCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somthing wrong with connection :(.
        /// </summary>
        internal static string NetworkProblems {
            get {
                return ResourceManager.GetString("NetworkProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t parse server response :(.
        /// </summary>
        internal static string ParsingXmlProblems {
            get {
                return ResourceManager.GetString("ParsingXmlProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and exit.
        /// </summary>
        internal static string SaveAndExit {
            get {
                return ResourceManager.GetString("SaveAndExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveChanges?.
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
    }
}
